### ISSUE TITLE
ImportError: No module named pwd

### ISSUE THREAD

**Issue by coto** [GoogleCloudPlatform/appengine-sockets-python-java-go#7]
Running with Python 2.7.6 and App Engine SDK 1.9.18 I have this error:

INFO     2015-02-25 15:08:18,340 module.py:737] default: "POST /_ah/channel/connected/ HTTP/1.1" 404 52
INFO     2015-02-25 15:08:24,482 main.py:129] got newsgroup: sci.physics
ERROR    2015-02-25 15:08:26,125 main.py:148] something went wrong...
Traceback (most recent call last):
  File "/Users/coto/Desktop/appengine-sockets-python-java-go-master/python_socket_demo/main.py", line 137, in getPosts
    s = nntplib.NNTP(NNTP_SERVER)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/nntplib.py", line 146, in __init__
    import netrc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py", line 7, in <module>
    import pwd
  File "/Users/coto/google-cloud-sdk/platform/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 945, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named pwd

**Comment by geraldoandradee** [comment]
Same problem.

**Comment by adrianmarple** [comment]
Same here on Mac with App Engine SDK 1.9.30
