### ISSUE TITLE
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException

### ISSUE THREAD

**Issue by g-ericso** [GoogleCloudPlatform/appengine-sockets-python-java-go#9]
Followed the Java example and getting this error:

```sh
[INFO] Mar 23, 2017 5:02:20 PM org.apache.jasper.compiler.JDTCompiler$1 findType
[INFO] SEVERE: Compilation error
[INFO] org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
[INFO] 	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:342)
[INFO] 	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:206)
[INFO] 	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:163)
[INFO] 	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:96)
[INFO] 	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
[INFO] 	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:97)
[INFO] 	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:167)
[INFO] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:2187)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:974)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1164)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:366)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:623)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:392)
[INFO] 	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:429)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:349)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:327)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:314)
[INFO] 	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:592)
[INFO] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
[INFO] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
[INFO] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet.access$101(PrivilegedJspServlet.java:23)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet$2.run(PrivilegedJspServlet.java:61)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet.service(PrivilegedJspServlet.java:58)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
[INFO] 	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
[INFO] 	at com.google.appengine.tools.development.StaticFileUtils.serveWelcomeFileAsForward(StaticFileUtils.java:82)
[INFO] 	at com.google.appengine.tools.development.LocalResourceFileServlet.maybeServeWelcomeFile(LocalResourceFileServlet.java:254)
[INFO] 	at com.google.appengine.tools.development.LocalResourceFileServlet.doGet(LocalResourceFileServlet.java:120)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:490)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
[INFO] 
[INFO] 2017-03-23 17:02:20.953:WARN::/
[INFO] org.apache.jasper.JasperException: Unable to compile class for JSP: ||An error occurred at line: 1 in the generated java file|The type java.io.ObjectInputStream cannot be resolved. It is indirectly referenced from required .class files||Stacktrace:
[INFO] 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:92)
[INFO] 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:330)
[INFO] 	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:439)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:349)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:327)
[INFO] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:314)
[INFO] 	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:592)
[INFO] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
[INFO] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
[INFO] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet.access$101(PrivilegedJspServlet.java:23)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet$2.run(PrivilegedJspServlet.java:61)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at com.google.appengine.tools.development.PrivilegedJspServlet.service(PrivilegedJspServlet.java:58)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
[INFO] 	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
[INFO] 	at com.google.appengine.tools.development.StaticFileUtils.serveWelcomeFileAsForward(StaticFileUtils.java:82)
[INFO] 	at com.google.appengine.tools.development.LocalResourceFileServlet.maybeServeWelcomeFile(LocalResourceFileServlet.java:254)
[INFO] 	at com.google.appengine.tools.development.LocalResourceFileServlet.doGet(LocalResourceFileServlet.java:120)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:490)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by lesv** [comment]
Hi - sorry - this archive isn't being maintained.
